// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pywhllaoxcmosihgoatm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5d2hsbGFveGNtb3NpaGdvYXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDM1MTIsImV4cCI6MjA2NzM3OTUxMn0.mt9t9swevjmw8jbX0KtmgAZ7xVeXplDj3fx4ipiUiAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});